apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    keyvaultName: healthcare-kv
    tenantId: <TENANT_ID>
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
